sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>System  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Flow_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Name__c</fullName>
    <description>The name of the flow from which the log event was generated.</description>
    <label>Flow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Flow_Stage__c.field-meta.xml
<CustomField>
    <fullName>Flow_Stage__c</fullName>
    <label>Flow Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>The severity of the log message.</description>
    <inlineHelpText>The severity of the log message.</inlineHelpText>
    <label>Log Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warn</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Logged_From__c.field-meta.xml
<CustomField>
    <fullName>Logged_From__c</fullName>
    <description>What type of process logged this event?</description>
    <inlineHelpText>What type of process logged this event?</inlineHelpText>
    <label>Logged From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Script</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The reported log message.</description>
    <inlineHelpText>The reported log message.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Related_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Id__c</fullName>
    <description>The Id of the related Object for which the log message was generated.</description>
    <inlineHelpText>The Id of the related Object for which the log message was generated.</inlineHelpText>
    <label>Related Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Running_UserName__c.field-meta.xml
<CustomField>
    <fullName>Running_UserName__c</fullName>
    <description>The UserName (login name) of the running user when the log was generated.</description>
    <inlineHelpText>The UserName (login name) of the running user when the log was generated.</inlineHelpText>
    <label>Running UserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The stack trace when the log was generated.</description>
    <inlineHelpText>The stack trace when the log was generated.</inlineHelpText>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/recordTypes/Apex.recordType-meta.xml
<RecordType>
    <fullName>Apex</fullName>
    <active>true</active>
    <label>Apex</label>
</RecordType>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/recordTypes/Flow.recordType-meta.xml
<RecordType>
    <fullName>Flow</fullName>
    <active>true</active>
    <label>Flow</label>
</RecordType>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/recordTypes/Script.recordType-meta.xml
<RecordType>
    <fullName>Script</fullName>
    <active>true</active>
    <label>Script</label>
</RecordType>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/System_Log_Event__e.object-meta.xml
<CustomObject>
    <label>System Log Event</label>
    <pluralLabel>System Log Events</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Apex_Log_Event__c.field-meta.xml
<CustomField>
    <fullName>Apex_Log_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apex Log Event</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Flow_Log_Event__c.field-meta.xml
<CustomField>
    <fullName>Flow_Log_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Log Event</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Flow_Stage__c.field-meta.xml
<CustomField>
    <fullName>Flow_Stage__c</fullName>
    <label>Flow Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Related_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Id__c</fullName>
    <label>Related Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Running_UserName__c.field-meta.xml
<CustomField>
    <fullName>Running_UserName__c</fullName>
    <label>Running UserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Script_Log_Event__c.field-meta.xml
<CustomField>
    <fullName>Script_Log_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Script Log Event</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/TransitionAppSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General user-adjustable settings for the Transition Application.</description>
    <label>Transition App Settings</label>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Async_Requests_Are_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Async_Requests_Are_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables/Disables the continuation of processing of Async Request Queueable Apex</description>
    <inlineHelpText>WARNING: When unchecked, this managed package will not properly function.</inlineHelpText>
    <label>Async Requests Are Enabled</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/System_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>System_Log_Level__c</fullName>
    <description>The lowest LoggingLevel that should be tracked in System Log records</description>
    <inlineHelpText>Error, Warn, Debug, Info, or None</inlineHelpText>
    <label>System Log Level</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/SystemLoggerUtilsTest.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
@IsTest
private class SystemLoggerUtilsTest {
    @isTest static void testCreateSystemLogs() {
        String testClassName = 'TestClass';
        String testMethodName = 'TestClass';
        String testLineNumber = 'line 42';
        String testMsg = 'Test ERROR: ERROR';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.ERROR).toLowerCase().capitalize();
        String testStackTrace = 'Stack Trace Here';

        List<System_Log_Event__e> testSystemLogEvents = new List<System_Log_Event__e>();
        testSystemLogEvents.add(new System_Log_Event__e
            (
                Apex_Log_Event__c = true,
                Apex_Class__c = testClassName,
                Apex_Method__c = testMethodName,
                Line_Number__c = testLineNumber,
                Log_Level__c = testLogLevel,
                Message__c = testMsg,
                Running_UserName__c = testUserName,
                Stack_Trace__c = testStackTrace
            ));

        Test.startTest();
        SystemLoggerUtils.createSystemLogs(testSystemLogEvents);
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run!
        List<System_Log__c> sysLogRecords = [
            SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
            FROM System_Log__c
        ];
        System.assertNotEquals(sysLogRecords, null);
        System.assertNotEquals(sysLogRecords.isEmpty(), true);

        System.assertEquals(sysLogRecords[0].Logged_From__c, 'Apex');
        System.assertEquals(sysLogRecords[0].Apex_Class__c, testClassName);
        System.assertEquals(sysLogRecords[0].Apex_Method__c, testMethodName);
        System.assertEquals(sysLogRecords[0].Line_Number__c, testLineNumber);
        System.assertEquals(sysLogRecords[0].Log_Level__c, testLogLevel);
        System.assertEquals(sysLogRecords[0].Message__c, testMsg);
        System.assertEquals(sysLogRecords[0].Running_UserName__c, testUserName);
        System.assertEquals(sysLogRecords[0].Stack_Trace__c, testStackTrace);
    }

    @isTest static void testCreateLogEvent() {
        String testLoggedFrom = '';
        String testMsg = 'Test ERROR: ERROR';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.ERROR).toLowerCase().capitalize();
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n'
            + 'Class.TestClassName2.TestClassMethod2: line 42, column 1';
        System_Log_Event__e sysLogEvent;

        Test.startTest();

        testLoggedFrom = 'Apex';
        sysLogEvent = SystemLoggerUtils.createLogEvent(LoggingLevel.ERROR, testStackTrace, testMsg, null, testLoggedFrom);

        System.assertNotEquals(sysLogEvent, null);
        System.assertEquals(sysLogEvent.Apex_Log_Event__c, true);
        System.assertEquals(sysLogEvent.Apex_Class__c, 'TestClassName2');
        System.assertEquals(sysLogEvent.Apex_Method__c, 'TestClassMethod2');
        System.assertEquals(sysLogEvent.Line_Number__c, 'line 42');
        System.assertEquals(sysLogEvent.Log_Level__c, testLogLevel);
        System.assertEquals(sysLogEvent.Message__c, testMsg);
        System.assertEquals(sysLogEvent.Running_UserName__c, testUserName);
        System.assertEquals(sysLogEvent.Stack_Trace__c, testStackTrace);

        testLoggedFrom = 'Script';
        sysLogEvent = SystemLoggerUtils.createLogEvent(LoggingLevel.ERROR, testStackTrace, testMsg, null, testLoggedFrom);

        System.assertNotEquals(sysLogEvent, null);
        System.assertEquals(sysLogEvent.Script_Log_Event__c, true);
        System.assertEquals(sysLogEvent.Log_Level__c, testLogLevel);
        System.assertEquals(sysLogEvent.Message__c, testMsg);
        System.assertEquals(sysLogEvent.Running_UserName__c, testUserName);
        System.assertEquals(sysLogEvent.Stack_Trace__c, testStackTrace);

        testLoggedFrom = 'Flow';
        sysLogEvent = SystemLoggerUtils.createLogEvent(LoggingLevel.ERROR, testStackTrace, testMsg, null, testLoggedFrom);

        System.assertNotEquals(sysLogEvent, null);
        System.assertEquals(sysLogEvent.Flow_Log_Event__c, true);
        System.assertEquals(sysLogEvent.Log_Level__c, testLogLevel);
        System.assertEquals(sysLogEvent.Message__c, testMsg);
        System.assertEquals(sysLogEvent.Running_UserName__c, testUserName);
        System.assertEquals(sysLogEvent.Stack_Trace__c, testStackTrace);

        Test.stopTest();
    }

    @isTest static void testGetCallingTraceLine() {
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n';
        testStackTrace += 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String traceLine = SystemLoggerUtils.getCallingTraceLine(testStackTrace);
        Test.stopTest();

        System.assertNotEquals(traceLine, null);
        System.assertEquals(traceLine.contains('TestClassName2.TestClassMethod2'), true);
    }

    //==========================================================================
    // Method: testGetMethodName()
    @isTest static void testGetMethodName() {
        String testTraceLine = 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String methodName = SystemLoggerUtils.getMethodName(testTraceLine);
        Test.stopTest();

        System.assertNotEquals(methodName, null);
        System.assertEquals(methodName, 'TestClassMethod2');
    }

    //==========================================================================
    // Method: testGetLineNumberString()
    @isTest static void testGetLineNumberString() {
        String testTraceLine = 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String lineNumber = SystemLoggerUtils.getLineNumberString(testTraceLine);
        Test.stopTest();

        System.assertNotEquals(lineNumber, null);
        System.assertEquals(lineNumber, 'line 42');
    }

    //==========================================================================
    // Method: testGetClassName()
    @isTest static void testGetClassName() {
        String testTraceLine = 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        String className = SystemLoggerUtils.getClassName(testTraceLine);
        Test.stopTest();

        System.assertNotEquals(className, null);
        System.assertEquals(className, 'TestClassName2');
    }

    //========================================================================================
    // Method: testAddDebugLine()
    @isTest static void testAddDebugLine() {
        String testTraceLine = 'Class.TestClassName.TestClassMethod: line 42, column 1';
        String testMsg = 'Test ERROR: ERROR';

        Test.startTest();
            try {
                SystemLoggerUtils.addDebugLine(LoggingLevel.DEBUG, testTraceLine, testMsg);
                System.assert(true);
            }
            catch (Exception e) {
                System.assert(false, e.getMessage());
            }
        Test.stopTest();
    }

    //========================================================================================
    // Method: testCreateAndPublishLogEvent()
    @isTest static void testCreateAndPublishLogEvent() {
        TransitionAppSettings__c settings = new TransitionAppSettings__c(System_Log_Level__c='Warn',Async_Requests_Are_Enabled__c=true);
        insert settings;
        String testLoggedFrom = 'Apex';
        String testMsg = 'Test ERROR: Some ERROR.';
        System.LoggingLevel testLogLevel = LoggingLevel.ERROR;
        System.LoggingLevel testLogLevelWarn = LoggingLevel.WARN;
        System.LoggingLevel testLogLevelInfo = LoggingLevel.INFO;
        System.LoggingLevel testLogLevelDebug = LoggingLevel.DEBUG;
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n'
            + 'Class.TestClassName2.TestClassMethod2: line 42, column 1';

        Test.startTest();
        SystemLoggerUtils.createAndPublishLogEvent(testLogLevel, testStackTrace, testMsg, null, testLoggedFrom);
        SystemLoggerUtils.createAndPublishLogEvent(testLogLevelWarn, testStackTrace, testMsg, null, testLoggedFrom);
        SystemLoggerUtils.createAndPublishLogEvent(testLogLevelInfo, testStackTrace, testMsg, null, testLoggedFrom);
        SystemLoggerUtils.createAndPublishLogEvent(testLogLevelDebug, testStackTrace, testMsg, null, testLoggedFrom);
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run! (can't query events)
        List<System_Log__c> sysLogRecords = [
            SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
            FROM System_Log__c
        ];
        System.assertNotEquals(sysLogRecords, null);
        // System.assertEquals(sysLogRecords.isEmpty(), false);
        // System.assertEquals(sysLogRecords[0].Message__c, testMsg);
        // System.assertEquals(sysLogRecords[0].Logged_From__c, testLoggedFrom);
    }

    //========================================================================================
    // Method: testPublishEvent()
    @isTest static void testPublishEvent() {
        String testClassName = 'TestClass';
        String testMethodName = 'TestClass';
        String testLineNumber = 'line 42';
        String testMsg = 'Test ERROR: ERROR';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.ERROR).toLowerCase().capitalize();
        String testStackTrace = 'Stack Trace Here';

        List<System_Log_Event__e> testSystemLogEvents = new List<System_Log_Event__e>();
        testSystemLogEvents.add(new System_Log_Event__e
            (
                Apex_Log_Event__c = true,
                Apex_Class__c = testClassName,
                Apex_Method__c = testMethodName,
                Line_Number__c = testLineNumber,
                Log_Level__c = testLogLevel,
                Message__c = testMsg,
                Running_UserName__c = testUserName,
                Stack_Trace__c = testStackTrace
            ));

        Test.startTest();
        SystemLoggerUtils.publishEvents(testSystemLogEvents);
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run! (can't query events)
        List<System_Log__c> sysLogRecords = [
            SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
            FROM System_Log__c
        ];
        System.assertNotEquals(sysLogRecords, null);
        
        systemLoggerUtils.updateSystemLogs(sysLogRecords.get(0));
        systemLoggerUtils.updateSystemLogs(sysLogRecords);
    }

    @isTest static void testPublishEventAsync() {
        String testClassName = 'TestClass';
        String testMethodName = 'TestClass';
        String testLineNumber = 'line 42';
        String testMsg = 'Test ERROR: ERROR';
        String testUserName = UserInfo.getUserName();
        String testLogLevel = String.valueOf(LoggingLevel.ERROR).toLowerCase().capitalize();
        String testStackTrace = 'Stack Trace Here';

        List<System_Log_Event__e> testSystemLogEvents = new List<System_Log_Event__e>();
        testSystemLogEvents.add(new System_Log_Event__e
            (
                Apex_Log_Event__c = true,
                Apex_Class__c = testClassName,
                Apex_Method__c = testMethodName,
                Line_Number__c = testLineNumber,
                Log_Level__c = testLogLevel,
                Message__c = testMsg,
                Running_UserName__c = testUserName,
                Stack_Trace__c = testStackTrace
            ));

        Test.startTest();
        // !!! Create enough records to use up the DML limit !!!
        /*List<Lead> testLeads = new List<Lead>();
        for (Integer i=0; i < Limits.getLimitDmlRows(); i++)
        {
            testLeads.add(new Lead
                    (
                            FirstName = 'Tester'+i,
                            LastName='Testing'+i,
                            Email='me' + i + '@here.now',
                            Company ='Test Company XX',
                            Status = 'New',
                            LeadSource = 'Other',
                            Industry = 'Aerospace'
                    ));
        }
        insert testLeads; // Use up the DML limit*/
        SystemLoggerUtils.publishEvents(testSystemLogEvents); // Now try to publish
        Test.stopTest();

        // Technically, these asserts require the System_Log_Event__e trigger to run! (can't query events)
        List<System_Log__c> sysLogRecords = [
            SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
            FROM System_Log__c
        ];
        System.assertNotEquals(sysLogRecords, null);
        // System.assertEquals(sysLogRecords.isEmpty(), false);
        // System.assertEquals(sysLogRecords[0].Message__c, testMsg);
        // System.assertEquals(sysLogRecords[0].Logged_From__c, 'Apex');
    }
}