sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>System  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Flow_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Name__c</fullName>
    <description>The name of the flow from which the log event was generated.</description>
    <label>Flow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Flow_Stage__c.field-meta.xml
<CustomField>
    <fullName>Flow_Stage__c</fullName>
    <label>Flow Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <description>The severity of the log message.</description>
    <inlineHelpText>The severity of the log message.</inlineHelpText>
    <label>Log Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warn</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Logged_From__c.field-meta.xml
<CustomField>
    <fullName>Logged_From__c</fullName>
    <description>What type of process logged this event?</description>
    <inlineHelpText>What type of process logged this event?</inlineHelpText>
    <label>Logged From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Script</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The reported log message.</description>
    <inlineHelpText>The reported log message.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Related_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Id__c</fullName>
    <description>The Id of the related Object for which the log message was generated.</description>
    <inlineHelpText>The Id of the related Object for which the log message was generated.</inlineHelpText>
    <label>Related Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Running_UserName__c.field-meta.xml
<CustomField>
    <fullName>Running_UserName__c</fullName>
    <description>The UserName (login name) of the running user when the log was generated.</description>
    <inlineHelpText>The UserName (login name) of the running user when the log was generated.</inlineHelpText>
    <label>Running UserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The stack trace when the log was generated.</description>
    <inlineHelpText>The stack trace when the log was generated.</inlineHelpText>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/recordTypes/Apex.recordType-meta.xml
<RecordType>
    <fullName>Apex</fullName>
    <active>true</active>
    <label>Apex</label>
</RecordType>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/recordTypes/Flow.recordType-meta.xml
<RecordType>
    <fullName>Flow</fullName>
    <active>true</active>
    <label>Flow</label>
</RecordType>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log__c/recordTypes/Script.recordType-meta.xml
<RecordType>
    <fullName>Script</fullName>
    <active>true</active>
    <label>Script</label>
</RecordType>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/System_Log_Event__e.object-meta.xml
<CustomObject>
    <label>System Log Event</label>
    <pluralLabel>System Log Events</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Flow_Log_Event__c.field-meta.xml
<CustomField>
    <fullName>Flow_Log_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Log Event</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Flow_Stage__c.field-meta.xml
<CustomField>
    <fullName>Flow_Stage__c</fullName>
    <label>Flow Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Related_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Id__c</fullName>
    <label>Related Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Running_UserName__c.field-meta.xml
<CustomField>
    <fullName>Running_UserName__c</fullName>
    <label>Running UserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/System_Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/TransitionAppSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General user-adjustable settings for the Transition Application.</description>
    <label>Transition App Settings</label>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Async_Requests_Are_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Async_Requests_Are_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables/Disables the continuation of processing of Async Request Queueable Apex</description>
    <inlineHelpText>WARNING: When unchecked, this managed package will not properly function.</inlineHelpText>
    <label>Async Requests Are Enabled</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/System_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>System_Log_Level__c</fullName>
    <description>The lowest LoggingLevel that should be tracked in System Log records</description>
    <inlineHelpText>Error, Warn, Debug, Info, or None</inlineHelpText>
    <label>System Log Level</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/SystemLoggerTest.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
@IsTest
private class SystemLoggerTest {
    @IsTest static void testLogFromApex() {
        TransitionAppSettings__c settings = new TransitionAppSettings__c(System_Log_Level__c='Warn',Async_Requests_Are_Enabled__c=true);
        insert settings;
        Account account = new Account(Name = 'TestAccount');
        insert account;
        System.assertNotEquals(account.Id, null);
        String testMsg = 'Test Error: Error';
        String testId = account.Id;

        Test.startTest();
        System.debug(LoggingLevel.WARN, 'SystemLoggerTest.testLogFromApex() - About to generate System logs! ...');
        SystemLogger.log(LoggingLevel.ERROR, testMsg, testId);
        SystemLogger.log(LoggingLevel.WARN, testMsg, testId);
        SystemLogger.log(LoggingLevel.INFO, testMsg, testId);
        SystemLogger.log(LoggingLevel.DEBUG, testMsg, testId);
        SystemLogger.log(LoggingLevel.NONE, testMsg);
        System.debug(LoggingLevel.WARN, 'SystemLoggerTest.testLogFromApex() - ... Done generate System logs!');
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        List<System_Log__c> sysLogRecords = [
            SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
            FROM System_Log__c
        ];

        System.assertNotEquals(null, sysLogRecords);
        // System.assertEquals(2, sysLogRecords.size());
        // System.assertEquals('Apex', sysLogRecords[0].Logged_From__c);
        // System.assertEquals(testMsg, sysLogRecords[0].Message__c);
        // System.assertEquals(testId, sysLogRecords[0].Related_Object_Id__c);
    }

    @IsTest static void testLogWebService() {
        TransitionAppSettings__c settings = new TransitionAppSettings__c(System_Log_Level__c='Warn',Async_Requests_Are_Enabled__c=true);
        insert settings;
        String testMsg = 'Something bad happened.';
        List<String> testLogLevels = new List<String>{
            'Error', 'Warn', 'Info', 'Debug', 'None'
        };
        String componentInfo = 'Component#method';
        Account account = new Account(Name = 'TestAccount');
        insert account;
        System.assertNotEquals(account.Id, null);

        Test.startTest();
        System.debug(LoggingLevel.WARN, 'SystemLoggerTest.testLogFromScript() - About to generate System logs! ...');
        SystemLogger.createLog(testLogLevels[0], testMsg, account.Id, componentInfo);
        SystemLogger.createLog(testLogLevels[1], testMsg, account.Id, componentInfo);
        SystemLogger.createLog(testLogLevels[2], testMsg, account.Id, componentInfo);
        SystemLogger.createLog(testLogLevels[3], testMsg, account.Id, componentInfo);
        SystemLogger.createLog(testLogLevels[4], testMsg, account.Id, componentInfo);
        System.debug(LoggingLevel.WARN, 'SystemLoggerTest.testLogFromScript() - ... Done generate System logs!');
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        List<System_Log__c> sysLogRecords = [
            SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
            FROM System_Log__c
        ];
        System.assertNotEquals(sysLogRecords, null);
        // System.assertEquals(2, sysLogRecords.size());
        // System.assertEquals(sysLogRecords[0].Logged_From__c, 'Script');
        // System.assertEquals(sysLogRecords[0].Message__c, testMsg);
        // System.assertEquals(sysLogRecords[0].Related_Object_Id__c, account.Id);
    }

    /*
    @IsTest static void testLogInvocable() {
        String testMsg = 'Something bad happened.';
        List<String> testLogLevels = new List<String>{'Error','Warn','Info','Debug','None'};
        String testLoggedFrom = 'Flow';
        String testStackTrace = 'Class.TestClassName1.TestClassMethod1: line 123, column 1 \n'
                + 'Class.TestClassName2.TestClassMethod2: line 42, column 1';
        Contact testContact = new Contact(FirstName='Test',LastName='Test',Email='testing@here.now');
        insert testContact;
        System.assertNotEquals(testContact.Id,null);

        System_Logger_Setting__mdt setting = [SELECT Id,DeveloperName,User_Name__c,On_Debug__c,On_Error__c,On_Info__c,On_Warn__c
        FROM System_Logger_Setting__mdt
        WHERE User_Name__c = :SystemLoggerUtils.DEFAULT_SYSLOG_USERNAME
        LIMIT 1];
        Integer expectedLogCount = 0;
        expectedLogCount += (setting.On_Error__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Warn__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Info__c == 'System Log') ? 1 : 0;
        expectedLogCount += (setting.On_Debug__c == 'System Log') ? 1 : 0;

        List<System_Log_Event__e> eventsToPublish = new List<System_Log_Event__e>();
        for (String logLevel : testLogLevels)
        {
            eventsToPublish.add(new System_Log_Event__e
                    (
                            Flow_Log_Event__c = true,
                            Log_Level__c = logLevel,
                            Message__c = testMsg,
                            Running_UserName__c = UserInfo.getUserName(),
                            Stack_Trace__c = testStackTrace,
                            Related_Object_Id__c = testContact.Id
                    ));
        }

        Test.startTest();
        System.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - About to generate System logs! ...');
        SystemLogger.log(eventsToPublish);
        System.debug(LoggingLevel.WARN,'SystemLoggerTest.testLogFromApex() - ... Done generate System logs!');
        Test.getEventBus().deliver(); // <= Force deliver the messages in the event bus
        Test.stopTest();

        List<System_Log__c> sysLogRecords = [SELECT Id,Logged_From__c,Apex_Class__c,Apex_Method__c,Line_Number__c,
                Log_Level__c,Message__c,Related_Object_Id__c,Running_UserName__c,
                Stack_Trace__c,Flow_Name__c,Flow_Stage__c
        FROM System_Log__c];
        System.assertNotEquals(sysLogRecords,null);
        System.assertEquals(sysLogRecords.size(),expectedLogCount);
        System.assertEquals(sysLogRecords[0].Logged_From__c,testLoggedFrom);
        System.assertEquals(sysLogRecords[0].Message__c,testMsg);
        System.assertEquals(sysLogRecords[0].Related_Object_Id__c,testContact.Id);
    }
     */
}