sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/ParentRequest__c.field-meta.xml
<CustomField>
    <fullName>ParentRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Request</label>
    <referenceTo>AsyncRequest__c</referenceTo>
    <relationshipName>ChildRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/AsyncRequestTriggerHandler.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
public inherited sharing class AsyncRequestTriggerHandler extends TriggerHandler {
    private static TransitionAppSettings appSettings = new TransitionAppSettings();

    public override void afterInsert() {
        enqueueRequests(Trigger.new);
    }

    public override void afterUpdate() {
        retryAsyncRequests((Map<Id, AsyncRequest__c>)Trigger.oldMap, Trigger.new);
    }

    private static void enqueueRequests(List<AsyncRequest__c> asyncRequests) {
        for (AsyncRequest__c request : asyncRequests) {
            if (request.ParentRequest__c == null) {
                TransitionAppSettings.asyncTypesToEnqueue.add(request.AsyncType__c);
            }
        }

        for (String asyncType : TransitionAppSettings.asyncTypesToEnqueue) {
            AsyncRequestProcessor.enqueueJob(null, null, asyncType);
        }
    }

    private static void retryAsyncRequests(Map<Id, AsyncRequest__c> oldAsyncRequestsByIds, List<AsyncRequest__c> newAsyncRequests) {
        for (AsyncRequest__c newAsyncRequest : newAsyncRequests) {
            AsyncRequest__c oldAsyncRequest = oldAsyncRequestsByIds.get(newAsyncRequest.Id);

            if (oldAsyncRequest.Error__c && !newAsyncRequest.Error__c) {
                if (newAsyncRequest.ParentRequest__c != null) {
                    if (!TransitionAppSettings.parentIdsByDependentTypes.containsKey(newAsyncRequest.AsyncType__c))
                        TransitionAppSettings.parentIdsByDependentTypes.put(newAsyncRequest.AsyncType__c, new List<Id>());
                    TransitionAppSettings.parentIdsByDependentTypes.get(newAsyncRequest.AsyncType__c).add(newAsyncRequest.ParentRequest__c);
                } else {
                    TransitionAppSettings.asyncTypesToEnqueue.add(newAsyncRequest.AsyncType__c);
                }
            }
        }

        for (String asyncType : TransitionAppSettings.asyncTypesToEnqueue)
            AsyncRequestProcessor.enqueueJob(null, null, asyncType);

        for (String asyncType : TransitionAppSettings.parentIdsByDependentTypes.keySet()) {
            for (Id parentRequestId : TransitionAppSettings.parentIdsByDependentTypes.get(asyncType)) {
                AsyncRequestProcessor.enqueueJob(null, parentRequestId, asyncType);
            }
        }
    }
}