sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/AsyncRequestTriggerHandlerTest.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
@IsTest
private class AsyncRequestTriggerHandlerTest {
    @IsTest static void testInsertRequest() {
        AsyncRequest__c asyncRequest = new AsyncRequest__c();
        asyncRequest.AsyncType__c = TestProcessor.class.getName();

        Test.startTest();

        insert asyncRequest;

        Test.stopTest();

        System.assert(TransitionAppSettings.asyncTypesToEnqueue.contains(TestProcessor.class.getName()));
    }

    @IsTest static void testRetryAsyncRequests() {
        AsyncRequest__c asyncRequest = new AsyncRequest__c();
        asyncRequest.AsyncType__c = TestProcessor.class.getName();

        insert asyncRequest;

        asyncRequest.Error__c = true;
        update asyncRequest;

        Test.startTest();

        asyncRequest.Error__c = false;
        update asyncRequest;

        Test.stopTest();

        System.assert(TransitionAppSettings.asyncTypesToEnqueue.contains(TestProcessor.class.getName()));
    }
}