sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/AnalysisDataJSON__c.field-meta.xml
<CustomField>
    <fullName>AnalysisDataJSON__c</fullName>
    <label>AnalysisDataJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment_Report_Section__mdt/Assessment_Report_Section__mdt.object-meta.xml
<CustomObject>
    <label>Assessment Report Section</label>
    <pluralLabel>Assessment Report Sections</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment_Report_Section__mdt/fields/Render_Flags__c.field-meta.xml
<CustomField>
    <fullName>Render_Flags__c</fullName>
    <description>API names of one or more comma separated checkbox fields found on, or looked up from, Assessment__c</description>
    <label>Render Flags</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Feature__mdt/SFDC_Feature__mdt.object-meta.xml
<CustomObject>
    <description>Industry key components and features for transitioning to</description>
    <label>SFDC Feature</label>
    <pluralLabel>SFDC Features</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Feature__mdt/fields/Answer_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Answer_API_Name__c</fullName>
    <description>The SFDC Answer that should be selected to show the positive label, otherwise shows negative label</description>
    <inlineHelpText>The SFDC Answer that should be selected to show the positive label, otherwise shows negative label</inlineHelpText>
    <label>Answer API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Feature__mdt/fields/Render_Flags__c.field-meta.xml
<CustomField>
    <fullName>Render_Flags__c</fullName>
    <description>Additional logic for determining if positive label shows up</description>
    <inlineHelpText>Additional logic for determining if positive label shows up</inlineHelpText>
    <label>Render Flags</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/SFDC_Health_Cloud_Recommendation__mdt.object-meta.xml
<CustomObject>
    <description>Recommendations specifically geared towards providing Pre-Sales text (which can potentially be place in any spot within the assessment report)</description>
    <label>SFDC Health Cloud Recommendation</label>
    <pluralLabel>SFDC Health Cloud Recommendations</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/fields/Answer_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Answer_API_Name__c</fullName>
    <description>The Developer Name for the SFDC Industry Assessment Answer that should be true to display this recommendation.</description>
    <inlineHelpText>The Developer Name for the SFDC Industry Assessment Answer that should be true to display this recommendation.</inlineHelpText>
    <label>Answer API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>The SLDS icon to present next to this item</description>
    <inlineHelpText>The SLDS icon to present next to this item</inlineHelpText>
    <label>Icon Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/fields/List_Index__c.field-meta.xml
<CustomField>
    <fullName>List_Index__c</fullName>
    <description>The order in which this item should appear.</description>
    <label>List Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/fields/Recommendation_Label__c.field-meta.xml
<CustomField>
    <fullName>Recommendation_Label__c</fullName>
    <label>Recommendation Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/fields/Render_Flags__c.field-meta.xml
<CustomField>
    <fullName>Render_Flags__c</fullName>
    <description>Checks for fields on the Assessment object to determine whether to show this content or not.</description>
    <inlineHelpText>Checks for fields on the Assessment object to determine whether to show this content or not.</inlineHelpText>
    <label>Render Flags</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Health_Cloud_Recommendation__mdt/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <description>The report section in which this recommendation should appear.</description>
    <label>Section</label>
    <referenceTo>Assessment_Report_Section__mdt</referenceTo>
    <relationshipName>SFDC_Pre_Sales_Recommendations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Industry_Assessment_Answer__mdt/SFDC_Industry_Assessment_Answer__mdt.object-meta.xml
<CustomObject>
    <description>Contains options for answers within a particular question of an Assessment.</description>
    <label>SFDC Industry Assessment Answer</label>
    <pluralLabel>SFDC Industry Assessment Answers</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Industry_Assessment_Answer__mdt/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>SFDC_Industry_Assessment_Question__mdt</referenceTo>
    <relationshipLabel>SFDC Industry Assessment Answers</relationshipLabel>
    <relationshipName>SFDC_Industry_Assessment_Answers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Industry_Assessment_Answer__mdt/fields/Question_Label__c.field-meta.xml
<CustomField>
    <fullName>Question_Label__c</fullName>
    <label>Question Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Industry_Assessment_Question__mdt/SFDC_Industry_Assessment_Question__mdt.object-meta.xml
<CustomObject>
    <description>Questions asked in an industry upgrade transition assessment</description>
    <label>SFDC Industry Assessment Question</label>
    <pluralLabel>SFDC Industry Assessment Questions</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Industry_Assessment_Question__mdt/fields/Question_Group__c.field-meta.xml
<CustomField>
    <fullName>Question_Group__c</fullName>
    <label>Question Group</label>
    <referenceTo>SFDC_Industry_Assessment_Question_Group__mdt</referenceTo>
    <relationshipLabel>SFDC Industry Assessment Questions</relationshipLabel>
    <relationshipName>SFDC_Industry_Assessment_Questions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Industry_Assessment_Question_Group__mdt/SFDC_Industry_Assessment_Question_Group__mdt.object-meta.xml
<CustomObject>
    <description>Used to categorize questions for easy user navigation and organization</description>
    <label>SFDC Industry Assessment Question Group</label>
    <pluralLabel>SFDC Industry Assessment Question Groups</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/classes/PostScanDataRetrieval.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
/**
 * REST Service for providing Heroku functions with metadata/records that are protected
 * by the Transition Assistant's managed package rules.
 */
@RestResource(urlMapping='/PostScanData/*')
global with sharing class PostScanDataRetrieval {
    
    @TestVisible private static final String DATA_TYPE_FEATURES = 'features';
    @TestVisible private static final String DATA_TYPE_LIMITS = 'limitsMap';
    @TestVisible private static final String DATA_TYPE_LABELS = 'labels';
    @TestVisible private static final String DATA_TYPE_FIELD_COUNT = 'fieldcount';
    @TestVisible private static final String DATA_TYPE_INSTALL_READINESS = 'installReadiness';
    @TestVisible private static final String DATA_TYPE_OVERALL_REC = 'overallRec';

    //HC-Specific
    @TestVisible private static final String DATA_TYPE_ANSWERS = 'answers';
    @TestVisible private static final String DATA_TYPE_HC_RECS = 'hcRecs';
    

    @HttpGet
    global static String doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.statuscode = 200;

        String dataType = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

        //Get SFDC_Feature__mdt records
        if(dataType.equals(DATA_TYPE_FEATURES)){
            return JSON.serialize(SFDC_Feature__mdt.getAll().values());
        }else if(dataType.equals(DATA_TYPE_LIMITS)){
            return JSON.serialize(OrgLimits.getMap());
        }else if(dataType.equals(DATA_TYPE_FIELD_COUNT)){
            return ''+SchemaService.getOrgFieldCount();
        }else if(dataType.equals(DATA_TYPE_INSTALL_READINESS)){
            return JSON.serialize(TransitionReadinessUtility.getFscInstallationReadiness());
        }else if(dataType.equals(DATA_TYPE_ANSWERS)){
            return JSON.serialize([SELECT Id, DeveloperName, Question_Label__c, Question__r.Question_Group__r.MasterLabel FROM SFDC_Industry_Assessment_Answer__mdt]);
        }else if(dataType.equals(DATA_TYPE_HC_RECS)){
            return JSON.serialize([SELECT DeveloperName, Answer_API_Name__c, Icon_Name__c, Render_Flags__c, Recommendation_Label__c FROM SFDC_Health_Cloud_Recommendation__mdt WHERE Section__r.DeveloperName = 'AssessmentResults' Order By List_Index__c]);
        }

        res.statuscode = 404;
        return '';
    }

    @HttpPost
    global static String doPost(List<String> items){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.statuscode = 200;

        String dataType = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

        //Generate Overall Recommendation
        if(dataType.equals(DATA_TYPE_OVERALL_REC)){
            Assessment__c assessment = TransitionReadinessUtility.getAssessment(items[0]);
            TransitionReadinessUtility.ReadinessResults results = TransitionReadinessUtility.loadReadinessResults(assessment);
            if(!Test.isRunningTest()){
                TransitionReadinessUtility.injectApexSharingRecommendations(assessment, results);
                results.overallRecommendation = TransitionReadinessUtility.generateOverallRecommendation(results);
            }
            assessment.AnalysisDataJSON__c = results.toString();
            AssessmentService.updateAssessment(assessment);

            return 'success';
        }

        res.statuscode = 404;
        return '';
    }
}