sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Apex_Sharing_Scan_Complete__c.field-meta.xml
<CustomField>
    <fullName>Apex_Sharing_Scan_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Queueable and Batchable jobs checking for Apex Share Reasons has completed</description>
    <label>Apex Sharing Scan Complete</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Has_Apex_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Has_Apex_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Have Apex Sharing Reasons been detected?</inlineHelpText>
    <label>Has Apex Sharing</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Async Requests</relationshipLabel>
    <relationshipName>AsyncRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/ApexShareRecordQueryQueueableTest.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
@IsTest
private class ApexShareRecordQueryQueueableTest {

    @IsTest
    static void createAsyncRequestsTest() {
        Assessment__c assessment = new Assessment__c();
        insert assessment;
        ApexShareRecordQueryQueueable.QueryCriteria criteria = new ApexShareRecordQueryQueueable.QueryCriteria(
            assessment.Id,
            'Account',
            new List<String>{'test'}
        );

        Test.startTest();
            ApexShareRecordQueryQueueable.createAsyncRequests(assessment.Id, new List<ApexShareRecordQueryQueueable.QueryCriteria>{criteria});
        Test.stopTest();

        List<AsyncRequest__c> asyncRequests = [
            SELECT Id, Assessment__c, AsyncType__c
            FROM AsyncRequest__c
            WHERE Assessment__c = :assessment.Id
            AND AsyncType__c = 'ApexShareRecordQueryQueueable'
        ];
        System.assert(asyncRequests!=null);
    }

    @IsTest
    static void updateAssessmentTest() {
        Assessment__c assessment = new Assessment__c();
        insert assessment;
        ApexShareRecordQueryQueueable queueable = new ApexShareRecordQueryQueueable();
        queueable.queryCriteriaItem = new ApexShareRecordQueryQueueable.QueryCriteria(
            assessment.Id,
            'Account',
            new List<String>{'test'}
        );

        Test.startTest();
            queueable.updateAssessment(true, true);
        	ApexShareReferenceScanQueueable finalizer = new ApexShareReferenceScanQueueable();
        	finalizer.execute(new MockFinalizerContext(ParentJobResult.UNHANDLED_EXCEPTION));
       		finalizer.execute(new MockFinalizerContext(ParentJobResult.SUCCESS));
        Test.stopTest();

        assessment = [
            SELECT Id, Apex_Sharing_Scan_Complete__c, Has_Apex_Sharing__c
            FROM Assessment__c
            WHERE Id = :assessment.Id
        ];
        System.assertEquals(true, assessment.Apex_Sharing_Scan_Complete__c);
        System.assertEquals(true, assessment.Has_Apex_Sharing__c);
    }
    
    /** Mock FinalizerContext impl **/
    class MockFinalizerContext implements System.FinalizerContext {
        ParentJobResult result;
        public Id getAsyncApexJobId() { // valid Id, or query one 
            return '707000000000000';
        }
        public Exception getException() { return new System.AsyncException('heap breached'); }
        public String getRequestId() { return 'someRequestId'; }
        public ParentJobResult getResult() { return this.result; }
        MockFinalizerContext (ParentJobResult mockResult) {this.result = mockResult;}
    }
}