sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Org_Field_Count__c.field-meta.xml
<CustomField>
    <fullName>Org_Field_Count__c</fullName>
    <description>The number of total fields present in the org.</description>
    <inlineHelpText>The number of total fields present in the org.</inlineHelpText>
    <label>Org Field Count</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Async Requests</relationshipLabel>
    <relationshipName>AsyncRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/GetOrgFieldCountQueueable.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
/**
 * Gets the total number of fields in the org (async)
 */
public inherited sharing class GetOrgFieldCountQueueable extends AsyncRequestProcessor {
    public static Id asyncRequestId;
    private Id assessmentId;

    private void processRequest(AsyncRequest__c request) {
        this.assessmentId = request.Params__c;
        asyncRequestId = request.Id;

        getFullOrgFieldCount(this.assessmentId);
    }

    private static void getFullOrgFieldCount(Id assessmentId){
        Integer orgFieldCount = SchemaService.getOrgFieldCount();
        Assessment__c assessment = new Assessment__c(Id = assessmentId, Org_Field_Count__c = orgFieldCount);
        Database.update(assessment);
    }

    public static void createAsyncRequest(Id assessmentId) {
        AsyncRequest__c asyncRequest = new AsyncRequest__c(
            Assessment__c = assessmentId,
            AsyncType__c = GetOrgFieldCountQueueable.class.getName(),
            Params__c = assessmentId);

        insertAsyncRequest(asyncRequest);
    }
}