sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Apex_Sharing_Scan_Complete__c.field-meta.xml
<CustomField>
    <fullName>Apex_Sharing_Scan_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Queueable and Batchable jobs checking for Apex Share Reasons has completed</description>
    <label>Apex Sharing Scan Complete</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Bulk_Scan_Complete__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Scan_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that background scanning of org dependencies and upgrade readiness on this org has completed</description>
    <label>Bulk Scan Complete</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <description>Date in which the report for this assessment was generated</description>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Questionnaire</fullName>
            </value>
            <value>
                <fullName>Mapping</fullName>
            </value>
            <value>
                <fullName>Scanning</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Scanning Dependencies</fullName>
            </value>
            <value>
                <fullName>Scanning for Sharing Reasons</fullName>
            </value>
            <value>
                <fullName>Scanning Apex Sharing</fullName>
            </value>
            <value>
                <fullName>Generating Deployment Package</fullName>
            </value>
            <value>
                <fullName>Deployment Package Ready</fullName>
            </value>
            <value>
                <fullName>Finalizing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/AssessmentTriggerHandler.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
public inherited sharing class AssessmentTriggerHandler extends TriggerHandler {

    private static final String STATUS_SCANNING = 'Scanning';
    private static final String STATUS_REVIEW = 'Review';

    private static final String SUBSTATUS_INITIATE = 'Initializing';
    private static final String SUBSTATUS_BULK_SCAN = 'Scanning Dependencies';
    private static final String SUBSTATUS_SHARE_REASON_SCAN = 'Scanning for Sharing Reasons';
    private static final String SUBSTATUS_APEX_SHARE_SCAN = 'Scanning Apex Sharing';
    private static final String SUBSTATUS_FINALIZING = 'Finalizing';

    @TestVisible
    static Boolean bypassTriggerForTestSetup = false;

    public override void beforeUpdate() {
        if(bypassTriggerForTestSetup == true) return;

        Map<Id, Assessment__c> newMap = (Map<Id, Assessment__c>) Trigger.newMap;
        Map<Id, Assessment__c> oldMap = (Map<Id, Assessment__c>) Trigger.oldMap;

        List<Assessment__c> newList = newMap.values();
        PackageInstallationController.processPackageInstall(newList, oldMap);
        PackageDeploymentController.processPackageDeployment(newList, oldMap);

        for (Id assessmentId : newMap.keySet()) {
            Assessment__c newRecord = newMap.get(assessmentId);
            Assessment__c oldRecord = oldMap.get(assessmentId);

            if(newRecord.Status__c == STATUS_SCANNING && oldRecord.Status__c != STATUS_SCANNING){
                newRecord.Sub_Status__c = SUBSTATUS_BULK_SCAN;
            }

            //detect toggle Bulk_Scan_Complete__c to true
            if( (newRecord.Bulk_Scan_Complete__c && !oldRecord.Bulk_Scan_Complete__c)
                && newRecord.Status__c == STATUS_SCANNING
                && newRecord.Sub_Status__c == SUBSTATUS_INITIATE) {
                newRecord.Sub_Status__c = SUBSTATUS_APEX_SHARE_SCAN;
            }

            if( (newRecord.Apex_Sharing_Scan_Complete__c && !oldRecord.Apex_Sharing_Scan_Complete__c)
                && newRecord.Status__c == STATUS_SCANNING
                && newRecord.Sub_Status__c == SUBSTATUS_APEX_SHARE_SCAN) {
                    newRecord.Status__c = STATUS_SCANNING;
                    newRecord.Sub_Status__c = SUBSTATUS_FINALIZING;
            }

            if(oldRecord.Status__c != STATUS_REVIEW && newRecord.Status__c == STATUS_REVIEW){
                newRecord.Report_Date__c = Date.today();
            }
        }
    }

    public override void afterUpdate() {
        if(bypassTriggerForTestSetup == true) return;

        Map<Id, Assessment__c> newMap = (Map<Id, Assessment__c>) Trigger.newMap;
        Map<Id, Assessment__c> oldMap = (Map<Id, Assessment__c>) Trigger.oldMap;
        Map<Id, Assessment__c> recordsToProcessScanComplete = new Map<Id, Assessment__c>();

        //detect record field changes
        for (Id assessmentId : newMap.keySet()) {
            Assessment__c newRecord = newMap.get(assessmentId);
            Assessment__c oldRecord = oldMap.get(assessmentId);

            //detect toggle Bulk_Scan_Complete__c to true
            if(newRecord.Bulk_Scan_Complete__c && !oldRecord.Bulk_Scan_Complete__c) {
                ScanSharingReasonsQueueable.createAsyncRequest(newRecord.Id);

            } else if( (newRecord.Apex_Sharing_Scan_Complete__c && !oldRecord.Apex_Sharing_Scan_Complete__c)
                        || (newRecord.Sub_Status__c == SUBSTATUS_FINALIZING && oldRecord.Sub_Status__c != SUBSTATUS_FINALIZING) ){ //detect toggle Apex_Sharing_Scan_Complete__c to true
                if(newRecord.Bulk_Scan_Complete__c){
                    recordsToProcessScanComplete.put(newRecord.Id, newRecord);
                } else {
                    //Need to call CompleteAnalysis here
                    ScanComponentDependenciesQueueable.createAsyncRequest(newRecord.Id);
                }
            }
        }

        //Execute callback to finalize analysis processing after Bulk_Scan_Complete__c
        if (!recordsToProcessScanComplete.isEmpty()) {
            TransitionReadinessUtility.processScanResultsCallback(new List<Id>(recordsToProcessScanComplete.keySet()));
        }
    }
}