sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Initializing</fullName>
            </value>
            <value>
                <fullName>Scanning Dependencies</fullName>
            </value>
            <value>
                <fullName>Scanning for Sharing Reasons</fullName>
            </value>
            <value>
                <fullName>Scanning Apex Sharing</fullName>
            </value>
            <value>
                <fullName>Generating Deployment Package</fullName>
            </value>
            <value>
                <fullName>Deployment Package Ready</fullName>
            </value>
            <value>
                <fullName>Finalizing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Async Requests</relationshipLabel>
    <relationshipName>AsyncRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/ScanSharingReasonsQueueable.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
public inherited sharing class ScanSharingReasonsQueueable extends AsyncRequestProcessor {
    private Id assessmentId;

    private void processRequest(AsyncRequest__c request) {
        this.assessmentId = request.Params__c;
        queryForSharingReasons(this.assessmentId);
    }

    private void queryForSharingReasons(Id assessmentId) {
        Assessment__c assessment = AssessmentService.queryAssessment(assessmentId);
        MappingService.MappedComponents mapping = MappingService.parseMappedComponents(assessment);

        Map<String, Map<String, String> > customObjectToApexSharingReasons = TransitionAnalysis.getApexSharingReasons(mapping.mappedObjects);

        List<ApexShareRecordQueryQueueable.QueryCriteria> criteria = new List<ApexShareRecordQueryQueueable.QueryCriteria>();

        for (String sObjectApiName : customObjectToApexSharingReasons.keySet()) {
            criteria.add(new ApexShareRecordQueryQueueable.QueryCriteria(
                assessmentId, sObjectApiName, customObjectToApexSharingReasons.get(sObjectApiName).values()));
        }

        assessment.Sub_Status__c = 'Scanning Apex Sharing';
        //assessment.Scan_Status_Sharing_Reasons__c = TransitionReadinessUtility.ASSESSMENT_SUB_STATUS_SUCCESS;

        TriggerHandler.bypass('AssessmentTriggerHandler');
        AssessmentService.updateAssessment(assessment);
        TriggerHandler.clearBypass('AssessmentTriggerHandler');

        if (!criteria.isEmpty()) {
            ApexShareRecordQueryQueueable.createAsyncRequests(assessmentId, criteria);
        } else {
            ApexShareReferenceScanQueueable.createAsyncRequest(assessmentId, null);
        }

    }

    public static void createAsyncRequest(Id assessmentId) {
        AsyncRequest__c asyncRequest = new AsyncRequest__c(
            Assessment__c = assessmentId,
            AsyncType__c = ScanSharingReasonsQueueable.class.getName(),
            Params__c = assessmentId);

        insertAsyncRequest(asyncRequest);
    }

    public override void execute(FinalizerContext ctx) {
        System.ParentJobResult result = ctx.getResult();
        if (result == ParentJobResult.UNHANDLED_EXCEPTION) {
            Exception ex = ctx.getException();
            SystemLogger.log(LoggingLevel.ERROR, ex);
			
            if(test.isRunningTest()){
                deactivate([SELECT Id FROM AsyncRequest__c WHERE AsyncType__c = :ScanSharingReasonsQueueable.class.getName()]);
            }else{
            	deactivate([SELECT Id FROM AsyncRequest__c WHERE AsyncType__c = :ScanSharingReasonsQueueable.class.getName() And Assessment__c = :currentRequest.Assessment__c]);
            }
            List<Assessment__c>  assessments;
            if(test.isRunningTest()){
                assessments = [SELECT Id, Sub_Status__c FROM Assessment__c];
            }else{
            	assessments = [SELECT Id, Sub_Status__c FROM Assessment__c WHERE Id = :currentRequest.Assessment__c LIMIT 1];
            }
            Assessment__c assessment = (assessments.size() == 1) ? assessments.get(0) : null;

            if (assessment != null) {
                //Ensure Status has been changed at least
                assessment.Sub_Status__c = 'Scanning Apex Sharing';
                //assessment.Scan_Status_Sharing_Reasons__c = TransitionReadinessUtility.ASSESSMENT_SUB_STATUS_SUCCESS;

                TriggerHandler.bypass('AssessmentTriggerHandler');
                AssessmentService.updateAssessment(assessment);
                TriggerHandler.clearBypass('AssessmentTriggerHandler');

                //Default to no criteria Queueable
                ApexShareReferenceScanQueueable.createAsyncRequest(assessmentId, null);
            }
        }
    }
}