sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Bulk_Scan_Complete__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Scan_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that background scanning of org dependencies and upgrade readiness on this org has completed</description>
    <label>Bulk Scan Complete</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Async Requests</relationshipLabel>
    <relationshipName>AsyncRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/AssessmentTriggerTest.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
@isTest
private class AssessmentTriggerTest {
    static testMethod void testAssessmentAfterUpdate_BulkScanComplete() {
        Assessment__c assessment = new Assessment__c();
        insert assessment;

        Test.startTest();
            assessment.Bulk_Scan_Complete__c = true;
            update assessment;
        Test.stopTest();

        System.assert(true, 'This test should complete without exception invokes a void method. No results expected.');
    }
    
    @IsTest
    static void givenUnhandledExceptionVerifyFinalizer() {
        Assessment__c assessment = new Assessment__c();
        insert assessment;
        AsyncRequest__c asyncRequest = new AsyncRequest__c(AsyncType__c = ScanSharingReasonsQueueable.class.getName(), Assessment__c =assessment.Id);
        insert asyncRequest;

        Test.startTest();
            ScanSharingReasonsQueueable finalizer = new ScanSharingReasonsQueueable();
        	finalizer.execute(new MockFinalizerContext(ParentJobResult.UNHANDLED_EXCEPTION));
        Test.stopTest();

    }
    
    /** Mock FinalizerContext impl **/
    class MockFinalizerContext implements System.FinalizerContext {
        ParentJobResult result;
        public Id getAsyncApexJobId() { // valid Id, or query one 
            return '707000000000000';
        }
        public Exception getException() { return new System.AsyncException('heap breached'); }
        public String getRequestId() { return 'someRequestId'; }
        public ParentJobResult getResult() { return this.result; }
        MockFinalizerContext (ParentJobResult mockResult) {this.result = mockResult;}
    }
}