sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Salesforce Industries upgrade transition assessment and report</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment #{0}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Apex_Sharing_Scan_Complete__c.field-meta.xml
<CustomField>
    <fullName>Apex_Sharing_Scan_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Queueable and Batchable jobs checking for Apex Share Reasons has completed</description>
    <label>Apex Sharing Scan Complete</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/Assessment__c/fields/Has_Apex_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Has_Apex_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Have Apex Sharing Reasons been detected?</inlineHelpText>
    <label>Has Apex Sharing</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Async Requests</relationshipLabel>
    <relationshipName>AsyncRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/AsyncType__c.field-meta.xml
<CustomField>
    <fullName>AsyncType__c</fullName>
    <label>AsyncType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ApexShareRecordQueryQueueable</fullName>
            </value>
            <value>
                <fullName>ApexShareReferenceScanQueueable</fullName>
            </value>
            <value>
                <fullName>ScanComponentDependenciesQueueable</fullName>
            </value>
            <value>
                <fullName>ScanResultsQueueable</fullName>
            </value>
            <value>
                <fullName>ScanSharingReasonsQueueable</fullName>
            </value>
            <value>
                <fullName>TestProcessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/ApexShareRecordQueryQueueable.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
/**
 * @Desc:  Provided a list of Share objects, this queries those objects for custom Apex Share Reasons
**/
public inherited sharing class ApexShareRecordQueryQueueable extends AsyncRequestProcessor {

    @TestVisible
    private QueryCriteria queryCriteriaItem;
    
    private static final String ASSESSMENT_FILE_ANALYSIS = 'analysis';

    private void processRequest(AsyncRequest__c request){
        this.queryCriteriaItem = (QueryCriteria) JSON.deserialize(request.Params__c, QueryCriteria.class);

        if( hasSharingReasonsInUse() ){
            updateAssessment(true, false);
        }
    }

    /**
     * @Desc:  Queries __Share object for existence of custom Apex Sharing Reasons
     */
    private Boolean hasSharingReasonsInUse() {

        final String SHARE_QUERY = 'SELECT COUNT(Id), RowCause FROM {0} WHERE RowCause IN ({1}{2}{3}) GROUP BY RowCause';
        final String singleQuote = '\'';
        final String separator = '\',\'';
        String joinedSharingReasons = String.join( this.queryCriteriaItem.sharingReasons, separator );

        String queryString = String.format( SHARE_QUERY, new List<String> {
            queryCriteriaItem.sObjectApiName,
            singleQuote,
            joinedSharingReasons,
            singleQuote
        } );
        List<AggregateResult> sharingReasonQuery = Database.query( queryString );

        if ( !sharingReasonQuery.isEmpty() ) {
            return true;
        }

        return false;
    }

    /**
     *
     * @param hasApexSharing If object has a Custom Apex Share Reason
     * @param isScanComplete If all items have been scanned
     */
    @TestVisible
    private void updateAssessment(Boolean hasApexSharing, Boolean isScanComplete){
        Assessment__c assessment = new Assessment__c(Id = this.queryCriteriaItem.assessmentId);
        if(hasApexSharing){
            assessment.Has_Apex_Sharing__c = true;
        }
        if(isScanComplete){
            assessment.Apex_Sharing_Scan_Complete__c = true;
        }
        AssessmentService.updateAssessment(assessment);
    }

    /**
     * Wrapper to help with processing of multiple objects and Apex Share Reasons
     */
    public class QueryCriteria {
        public Id assessmentId;
        public String sObjectApiName;
        public List<String> sharingReasons;

        public QueryCriteria(Id assessmentId, String sObjectApiName, List<String> sharingReasons){
            this.assessmentId = assessmentId;
            this.sObjectApiName = sObjectApiName;
            this.sharingReasons = sharingReasons;
        }
    }

    public static void createAsyncRequests(Id assessmentId, List<ApexShareRecordQueryQueueable.QueryCriteria> criteria) {
        List<AsyncRequest__c> newAsyncRequests = new List<AsyncRequest__c>();

        for (ApexShareRecordQueryQueueable.QueryCriteria params : criteria)
            newAsyncRequests.add(new AsyncRequest__c(
                Assessment__c = assessmentId,
                AsyncType__c = ApexShareRecordQueryQueueable.class.getName(),
                Params__c = JSON.serialize(params)));

        AsyncRequestProcessor.insertAsyncRequests(newAsyncRequests);

        if (newAsyncRequests.isEmpty()) {
            ApexShareReferenceScanQueueable.createAsyncRequest(assessmentId, null);
        } else {
            ApexShareReferenceScanQueueable.createAsyncRequest(assessmentId, newAsyncRequests.get(newAsyncRequests.size() - 1).Id);
        }
    }
}