sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/SFDC_Help__mdt.object-meta.xml
<CustomObject>
    <description>Configured help text labels and links displayed within different areas of the application (e.g. sidebar help component)</description>
    <label>SFDC Help</label>
    <pluralLabel>SFDC Help</pluralLabel>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/fields/Description_Label__c.field-meta.xml
<CustomField>
    <fullName>Description_Label__c</fullName>
    <description>The name of the Custom Label for the description of this link.</description>
    <inlineHelpText>The name of the Custom Label for the description of this link.</inlineHelpText>
    <label>Description Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>The name of the SLDS icon to show with this link (if applicable).</description>
    <inlineHelpText>The name of the SLDS icon to show with this link (if applicable).</inlineHelpText>
    <label>Icon Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/fields/Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Link_URL__c</fullName>
    <description>The destination URL for this help item.</description>
    <inlineHelpText>The destination URL for this help item.</inlineHelpText>
    <label>Link URL</label>
    <type>Url</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Where this help item can be found in the application.</description>
    <inlineHelpText>Where this help item can be found in the application.</inlineHelpText>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Help Sidebar - Main Link</fullName>
                <default>true</default>
                <label>Help Sidebar - Main Link</label>
            </value>
            <value>
                <fullName>Help Sidebar - Side Link</fullName>
            </value>
            <value>
                <fullName>DeploymentChecklist</fullName>
                <label>Deployment Checklist</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/SFDC_Help__mdt/fields/Title_Label__c.field-meta.xml
<CustomField>
    <fullName>Title_Label__c</fullName>
    <description>The name of the Custom Label for the title of this link.</description>
    <inlineHelpText>The name of the Custom Label for the title of this link.</inlineHelpText>
    <label>Title Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/TransitionReadinessHelp.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
/***********************************************************************************
 * 
 * Class that controls content and actions shown in the "helpSidebar" component
 * 
 **********************************************************************************/
public with sharing class TransitionReadinessHelp {

    //Help Component Location Titles
    private static final String HELP_LOCATION_MAIN = 'Help Sidebar - Main Link';
    private static final String HELP_LOCATION_SIDE = 'Help Sidebar - Side Link';
    
    /*******************************************************************************
    * Main function for retrieving help content; retrieves from Heroku DB, and 
    * then deserializes + returns the HelpContent data.
    * 
    * Split into "mainLinks" (boxed items within component), and 
    * "supplementaryLinks" (in the "Related Articles" section)
    * 
    ******************************************************************************/
    @AuraEnabled
    public static HelpContent getHelpContent() {
        HelpContent sidebarContent = new HelpContent();
        String query = 'SELECT Title_Label__c, Index__c, Description_Label__c, Icon_Name__c, Link_URL__c, Location__c FROM SFDC_Help__mdt  WHERE Location__c IN (\''+HELP_LOCATION_MAIN+'\',\''+HELP_LOCATION_SIDE+'\') ORDER BY Index__c ASC';

        //Query Custom Metadata Type
        List<Object> metaRecords = ExternalUtilities.getCustomMetadata(new List<String>{query});
        List<SFDC_Help__mdt> helpMetadata = (List<SFDC_Help__mdt>) JSON.deserialize(JSON.serialize(metaRecords[0]), List<SFDC_Help__mdt>.class);
        System.debug(helpMetadata);
        
        for (SFDC_Help__mdt helpItem : helpMetadata) {
            //Retrieve label/translation info and create Help Item
            HelpItem tempItem = new HelpItem(
                ToolingService.customLabelMap.get(Utilities.namespaceUnderscore+helpItem.Title_Label__c), 
                ToolingService.customLabelMap.get(Utilities.namespaceUnderscore+helpItem.Description_Label__c), 
                helpItem.Icon_Name__c, 
                helpItem.Link_URL__c
            );
            
            //Place Help Item in appropriate List
            if(helpItem.Location__c == HELP_LOCATION_MAIN){
                sidebarContent.mainItems.add(tempItem);
            }else{
                sidebarContent.sideItems.add(tempItem);
            }
        }
        return sidebarContent;
    }


    /*******************************************************************************
    * Related wrapped objects. The "iconName" attribute under HelpItem is optional 
    * for all items in the "sideItems" list.
    ******************************************************************************/
    public class HelpContent {
        @AuraEnabled
        public List<HelpItem> mainItems {get;set;}

        @AuraEnabled
        public List<HelpItem> sideItems {get;set;}

        public HelpContent(){
            this.mainItems = new List<HelpItem>();
            this.sideItems = new List<HelpItem>();
        }
    }

    public class HelpItem {
        @AuraEnabled
        public String title {get;set;}
        @AuraEnabled
        public String description {get;set;}
        @AuraEnabled
        public String iconName {get;set;}
        @AuraEnabled
        public String link {get;set;}

        public HelpItem(String title, String description, String iconName, String link){
            this.title = title;
            this.description = description;
            this.iconName = iconName;
            this.link = link;
        }
    }
}