sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/TransitionAppSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General user-adjustable settings for the Transition Application.</description>
    <label>Transition App Settings</label>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Async_Requests_Are_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Async_Requests_Are_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables/Disables the continuation of processing of Async Request Queueable Apex</description>
    <inlineHelpText>WARNING: When unchecked, this managed package will not properly function.</inlineHelpText>
    <label>Async Requests Are Enabled</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Collapse_Welcome_Section_By_Default__c.field-meta.xml
<CustomField>
    <fullName>Collapse_Welcome_Section_By_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, collapses the &quot;Welcome&quot; section of the Assessment report, and allows the user to see the report results right away.</description>
    <inlineHelpText>If checked, collapses the &quot;Welcome&quot; section of the Assessment report, and allows the user to see the report results right away.</inlineHelpText>
    <label>Collapse Welcome Section By Default</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Exclusion_List_Active__c.field-meta.xml
<CustomField>
    <fullName>Exclusion_List_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, the Blacklisted Entries (custom metadata) will be subtracted from the Org Objects available for source mapping.</description>
    <label>Exclusion List Active</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/MetadataComponentDependencyBatchSize__c.field-meta.xml
<CustomField>
    <fullName>MetadataComponentDependencyBatchSize__c</fullName>
    <defaultValue>250</defaultValue>
    <label>Metadata Component Dependency Batch Size</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/System_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>System_Log_Level__c</fullName>
    <description>The lowest LoggingLevel that should be tracked in System Log records</description>
    <inlineHelpText>Error, Warn, Debug, Info, or None</inlineHelpText>
    <label>System Log Level</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/TransitionAppSettings.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
public inherited sharing class TransitionAppSettings {

    public static Set<String> asyncTypesToEnqueue = new Set<String>();
    public static Map<String, List<Id>> parentIdsByDependentTypes = new Map<String, List<Id>>();

    public Boolean collapseWelcomeSectionByDefault {
        get {
            return GetSettings().Collapse_Welcome_Section_By_Default__c;
        }
    }

    public Boolean asyncRequestsAreEnabled {
        get {
            return GetSettings().Async_Requests_Are_Enabled__c;
        }
    }

    public Boolean exclusionListActive {
        get {
            return GetSettings().Exclusion_List_Active__c;
        }
    }

    public String systemLogLevel {
        get {
            return GetSettings().System_Log_Level__c;
        }
    }

    public Decimal mdtComponentDependencyBatchSize {
        get {
            return GetSettings().MetadataComponentDependencyBatchSize__c;
        }
    }

    @TestVisible
    private static TransitionAppSettings__c testConfig = null;

    @TestVisible
    private TransitionAppSettings__c GetSettings() {
        if (Test.isRunningTest() && testConfig != null) return testConfig;

        TransitionAppSettings__c settings = TransitionAppSettings__c.getOrgDefaults();
        if(settings.SetupOwnerId == null) // No custom settings record yet
        {
            // settings = new TransitionAppSettings__c(
            //     SetupOwnerId = UserInfo.getOrganizationId()
            // );

            settings = new TransitionAppSettings__c(
                Collapse_Welcome_Section_By_Default__c = true,
                Async_Requests_Are_Enabled__c = true,
                SetupOwnerId = UserInfo.getOrganizationId(),
                System_Log_Level__c = 'Warn');

            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, new List<SObject>{settings}, true);

            if (!Test.isRunningTest()) insert decision.getRecords()[0];
            else testConfig = settings;
        }

        return settings;
    }

    public void updateCollapseWelcomeSectionByDefault(Boolean collapseWelcomeSectionByDefault) {
        TransitionAppSettings__c settings = GetSettings();
        settings.Collapse_Welcome_Section_By_Default__c = collapseWelcomeSectionByDefault;

        if (!Test.isRunningTest()) update settings;
    }

    public void updateSystemLogLevel(LoggingLevel loggingLevel) {
        TransitionAppSettings__c settings = GetSettings();
        settings.System_Log_Level__c = String.valueOf(loggingLevel);

        if (!Test.isRunningTest()) update settings;
    }

}