sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/TransitionAppSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General user-adjustable settings for the Transition Application.</description>
    <label>Transition App Settings</label>
</CustomObject>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Async_Requests_Are_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Async_Requests_Are_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables/Disables the continuation of processing of Async Request Queueable Apex</description>
    <inlineHelpText>WARNING: When unchecked, this managed package will not properly function.</inlineHelpText>
    <label>Async Requests Are Enabled</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Collapse_Welcome_Section_By_Default__c.field-meta.xml
<CustomField>
    <fullName>Collapse_Welcome_Section_By_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, collapses the &quot;Welcome&quot; section of the Assessment report, and allows the user to see the report results right away.</description>
    <inlineHelpText>If checked, collapses the &quot;Welcome&quot; section of the Assessment report, and allows the user to see the report results right away.</inlineHelpText>
    <label>Collapse Welcome Section By Default</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/Hide_Report_Summary__c.field-meta.xml
<CustomField>
    <fullName>Hide_Report_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked the Report Summary section of the Assessment Report will not be shown.</description>
    <inlineHelpText>If checked the Report Summary section of the Assessment Report will not be shown.</inlineHelpText>
    <label>Hide Report Summary</label>
    <type>Checkbox</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/objects/TransitionAppSettings__c/fields/System_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>System_Log_Level__c</fullName>
    <description>The lowest LoggingLevel that should be tracked in System Log records</description>
    <inlineHelpText>Error, Warn, Debug, Info, or None</inlineHelpText>
    <label>System Log Level</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdc-ac-transition-pkg/force-app/main/default/classes/PostInstallScript.cls
/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache 2.0 Clause
 * For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/
 */
global class PostInstallScript implements InstallHandler {
    global void onInstall(InstallContext context) {
        ApexClass cls = [SELECT Name, NamespacePrefix FROM ApexClass WHERE Name = 'PostInstallScript' 
        AND (NamespacePrefix LIKE 'HCTransition%' OR NamespacePrefix LIKE 'FSCTransition%' OR NamespacePrefix LIKE 'HealthCloudTA%' OR NamespacePrefix LIKE 'ACTransition%' OR NamespacePrefix LIKE 'AutoTADev%' OR NamespacePrefix LIKE 'AutomotiveCloudTA%' OR NamespacePrefix = '') 
        ORDER BY CreatedDate DESC LIMIT 1];
        String nameSpacePrefix = cls.NamespacePrefix;
        Id permissionSetId = [SELECT Id FROM PermissionSet WHERE Name LIKE '%Transition_Assistant' AND NamespacePrefix =: nameSpacePrefix].Id;
        List<PermissionSetAssignment> existingPSAList = [SELECT AssigneeId, PermissionSet.Name, PermissionSetId FROM PermissionSetAssignment WHERE PermissionSetId =: permissionSetId AND AssigneeId =: context.installerId()];
        
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = context.installerId(),
            PermissionSetId = permissionSetId
        );

        if(existingPSAList.size() <= 0) {
            insert psa;
        }

        //initialize custom settings
        //TransitionAppSettings settings = new TransitionAppSettings();
        TransitionAppSettings__c settings = TransitionAppSettings__c.getOrgDefaults();
        if(settings.SetupOwnerId == null) // No custom settings record yet
        {
            // settings = new TransitionAppSettings__c(
            //     SetupOwnerId = UserInfo.getOrganizationId()
            // );

            settings = new TransitionAppSettings__c(
                Collapse_Welcome_Section_By_Default__c = true,
                Async_Requests_Are_Enabled__c = true,
                SetupOwnerId = UserInfo.getOrganizationId(),
                System_Log_Level__c = 'Warn',
                Hide_Report_Summary__c = true);

            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, new List<SObject>{settings}, true);

            insert decision.getRecords()[0];
        }
    }
}